#!/system/bin/sh
#
# Copyright (C) 2015, Opersys inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Opersys Launcher Wrapper shell script
#

APKP=/data/app/com.opersys.otlauncher
for i in 1 2 3 4 5 6 7 8 9; do
  if [ -f $APKP-$i.apk ]; then
    APK=$APKP-$i.apk
    break
  fi
done

echo "APK: $APK"
DEBUG=

while [ ! -z "$1" ] ; do
  if [ $1 == "-f" ]; then
    APK="$2"
    shift
  elif [ $1 == "-r" ]; then
    APPID="-r $2"
    shift
  elif [ $1 == "-d" ]; then
    DEBUG=-d
  fi

  shift
done;

export CLASSPATH=$APK
CLASS=com.opersys.otlauncher.OTLauncher

app_process /data/local/tmp $CLASS -f $APK $DEBUG $APPID